### ISSUE TITLE
Hugs and kisses? No, bugs and fixes...

### ISSUE THREAD

**Issue by Afonin-Anthony** [YriyAntonov228/CyberSecurity#1]
Какой позор в 2021 году не пользоваться системами автоматической сборки, такими как например Maven, Gradle, или на крайняк билдить это говно  Ant-ом? Свинг для отрисовки UI? Пипец... Ничего лучшего не нашли? Где жабаFX? 21 век на дворе. Да и из за отсутствия длл-ок эта шняга не стартует ни под линуксом, ни под 32-х разрядной виндой. С нетерпением ждем недостающие длл-ки =)

**Comment by YriyAntonov228** [comment]
Доброго времени суток. В моём OpenClose проекте был принципиально не использован Maven для достижения:
операций, которые нельзя совершить в процессе сборки из IDE
Написания собственных плагинов и вручную проверять зависимости и совместимости для большей осведомленности разработчиков.
Целью разработки является создание разнообразных систем идентификации модулей и разграничивание информации и форматах о модулях в разных местах
Swing — самый оптимальный UI фреймворк, все "Bug-и" вызванные написанием нативного кода будут исправляться в ручную что даст больший опыт в разработке.
При более детальном рассмотрении кода, можно сразу понять почему не был использован JavaFX. Все просто: В нём мало дизайнерских инструментов, отсутствует поддержка Moonlight в должных стандартах
DLL : sfc /scannow
